# Generated by Django 5.1.2 on 2024-10-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('players', models.ManyToManyField(to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=30)),
                ('animal', models.CharField(max_length=30)),
                ('famous_person', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('related_to_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.room')),
            ],
        ),
    ]
