# Generated by Django 5.1.2 on 2024-11-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='players',
            field=models.ManyToManyField(related_name='rooms', to='game.player'),
        ),
        migrations.AlterField(
            model_name='words',
            name='related_to_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room'),
        ),
    ]
